/**
 * Live dashboard for the Node host. Serves the main HTML page and JSON
 * polling endpoints. All "/api/*.json" endpoints recompute from disk on
 * every request — pixelpipe doesn't have a query layer, but a 1.5 MB JSONL
 * streams in well under 100 ms.
 *
 * Legacy live-poll endpoints (left in place, the existing tick() loop uses
 * them):
 *
 *   GET  /, /dashboard               → main HTML page
 *   GET  /proxy-stats                → JSON aggregate over the in-mem ring
 *   GET  /proxy-recent               → JSON ring buffer of recent requests
 *   GET  /proxy-latest-png[?crop=N]  → raw PNG of the latest rendered image
 *
 * Session endpoints (read-only telemetry — no destructive operations):
 *
 *   GET  /api/sessions.json          → grouped sessions (sha8 + project + counts)
 *   GET  /api/stats.json             → full-history aggregate (formerly `pixelpipe stats`)
 *
 * Metric formulas and HTML shell originally ported from the Python reference
 * implementation (deleted after live cache-rate validation hit 98.7% by tokens).
 *
 * Node-only by design. Workers host has no dashboard; use Workers Logs.
 *
 * Memory bound: ring buffer cap 50 events + a parallel ring of the last 50
 * rendered PNGs (images are never persisted to disk, so this ring is the
 * only place to view them). At a typical 75 KB PNG that's ~3-4 MB resident;
 * a process restart starts the image ring empty.
 */

import * as fs from 'node:fs';
import * as readline from 'node:readline';
import type { ProxyEvent } from './core/proxy.js';
import type { TrackEvent } from './core/tracker.js';
import {
  computeActualInputEff,
  computeBaselineInputEff,
} from './core/baseline.js';
import {
  aggregateSessions,
  claudeCodeMap,
  filterSessions,
  type ClaudeCodeSessionRef,
  type ListOptions,
  type SessionsPaths,
} from './sessions.js';
import { aggregateEventsFile, summaryToJson } from './stats.js';
// Compiled Svelte UI - generated by `scripts/build-dashboard-ui.mjs`.
// Importing the .ts source lets esbuild inline the bundle string when it
// compiles `src/node.ts`. The generated file is committed so a clean install
// works without a separate UI build step at install time.
import { DASHBOARD_JS } from './dashboard-bundle.js';

const RECENT_CAP = 50;

/** How many rendered PNGs to keep in the in-memory image ring. Matches
 *  RECENT_CAP so every visible recent-requests row can still resolve its
 *  image. Images are never written to disk — this ring is the only store. */
const IMAGE_RING_CAP = 50;

/** One rendered image held in the in-memory ring. `id` is a monotonic
 *  counter (never reused) so a RecentRow can reference its image even after
 *  older entries are evicted; the dashboard pulls it via
 *  /proxy-latest-png?id=${id}. */
interface ImageEntry {
  id: number;
  png: Uint8Array;
  /** Human-readable "WxH · NN KB · N images total" line for the caption. */
  meta: string;
  width: number;
  height: number;
  ts: number;
}

/** One row in the dashboard's "recent requests" table. Compact on purpose —
 *  this lives in memory and gets serialized on every poll.
 *
 *  The "input" numbers (`actual_input`, `baseline_input`) are input-side
 *  only — input + cache_create×1.25 + cache_read×0.10 — because that's
 *  the slice the proxy can move. `output_tokens` is reported separately so
 *  the operator can see what fraction of the bill is unaffected by
 *  compression (and decide whether the headline % makes sense for their
 *  workload). */
export interface RecentRow {
  ts: number;
  method: string;
  path: string;
  status: number;
  size_in?: number;
  compressed: boolean;
  cc_added?: number;
  input_tokens?: number;
  /** From /v1/messages `usage.output_tokens`. Identical with/without
   *  compression — shown so the operator can see why an output-heavy
   *  turn moves the headline less than a cache-create-heavy one. */
  output_tokens?: number;
  cache_create?: number;
  cache_read?: number;
  /** input + cache_create×1.25 + cache_read×0.10, from the upstream usage
   *  block. Missing when the request 4xx'd or wasn't /v1/messages. */
  actual_input?: number;
  /** /v1/messages/count_tokens(originalBody).input_tokens. Missing when the
   *  side-probe failed or the request body wasn't an Anthropic Messages payload. */
  baseline_input?: number;
  /** How much the running "saved" total moved on this request. */
  session_saved_so_far_delta?: number;
  /** Id of the image rendered for this request, if any — resolves against
   *  the image ring via /proxy-latest-png?id=${img_id}. Absent when the
   *  request rendered no image, or once the image has been evicted from the
   *  ring (the id stays on the row but no longer fetches). */
  img_id?: number;
}

/** Aggregate over the whole session. Reset on process restart unless
 *  replay() is called to seed from the JSONL file.
 *
 *  The savings numerator is input-only — output is identical with and
 *  without compression, so it cancels. The denominator is the FULL bill
 *  (input + output×5 in input-token-equivalents) so the headline percentage
 *  drops honestly toward zero on output-heavy workloads instead of hiding
 *  the fact that the proxy only moves part of the cost.
 *
 *    Per event (see src/core/baseline.ts for the derivation):
 *      cacheable = baseline_cacheable_tokens || 0     (tokens up to last cache_control)
 *      cold_tail = baseline_tokens − cacheable        (always-cold input on both paths)
 *      cc_u, cr_u = the unproxied path's counterfactual cache_create / cache_read split:
 *                   cr > 0 ?  cc_u = min(cc, cacheable),  cr_u = cacheable − cc_u   (warm turn)
 *                 : cc > 0 ?  cc_u = cacheable,           cr_u = 0                  (cold start)
 *                 :           cc_u = 0,                   cr_u = 0                  (no caching)
 *      baseline_input_eff = cc_u × 1.25 + cr_u × 0.10
 *                         + (cacheable − cc_u − cr_u) × 1.0 + cold_tail × 1.0
 *      actual_input_eff   = input + cache_create×1.25 + cache_read×0.10
 *      output_equiv       = output × 5                (input-token-equivalent at the 5× output rate)
 *      saved              = baseline_input_eff − actual_input_eff
 *      baseline_total     = baseline_input_eff + output_equiv
 *      actual_total       = actual_input_eff + output_equiv
 *
 *    Roll-up:
 *      saved_pct = Σ saved / Σ baseline_total × 100
 *
 *  This is what Anthropic's weekly-limit meter actually counts — input +
 *  output×5 in input-token-equivalents. The dashboard headline matches it
 *  so a "20% saved" number means weekly-limit consumption dropped by 20%,
 *  not "20% off the slice we touched while the other half stayed full." */
/**
 * Per-session aggregate. Same dollar-weighted savings math as the global
 * `Totals` block, but partitioned by `info.firstUserSha8` so the dashboard
 * can show "what's happening RIGHT NOW" instead of stale lifetime numbers.
 * Field names mirror the JSON wire shape served by `serveCurrentSessionJson`.
 */
interface SessionTotals {
  sessionId: string;
  firstSeen: number; // unix seconds
  lastSeen: number; // unix seconds
  requests: number;
  // Dollar-weighted accumulators. baseline/actual are the SAME math as the
  // global `Totals.allBaselineEquivalentWeighted` / `allActualInputWeighted`
  // + `allOutputWeighted`, but scoped to a single session.
  baselineInputWeighted: number;
  actualInputWeighted: number;
  outputWeighted: number;
  // Per-bucket char attribution from ev.info.bucketChars.
  bucketChars: { [bucket: string]: number };
  // Passthrough reason histogram from ev.info.passthroughReasons.
  passthroughReasons: Record<string, number>;
  passthroughRequests: number; // count of requests where !ev.info.compressed
  compressedRequests: number;
}

interface Totals {
  requests: number;
  compressedRequests: number;
  /** Sum of weighted actual input tokens we paid for, across all events that
   *  also carried a baseline_tokens measurement (input + cache_create×1.25 +
   *  cache_read×0.10). */
  actualInputWeighted: number;
  /** Sum of the cache-aware baseline (see formula above) across the same
   *  events that contributed to `actualInputWeighted`. The honest counter-
   *  factual cost of the unproxied path. */
  baselineInputWeighted: number;
  /** Sum of output_tokens × OUTPUT_TOKEN_RATE across the same events. Added
   *  to BOTH sides of the savings math denominator so the headline % counts
   *  output toward the total bill (it cancels in the numerator — proxy
   *  doesn't touch output). Without this the headline ignores half the
   *  bill on output-heavy sessions. */
  outputWeighted: number;
  /** Sum of weighted COUNTERFACTUAL input tokens across ALL requests
   *  with a usage block. For measured rows: cache-aware baseline (what the
   *  unproxied path would have billed). For unmeasured/probe-failed rows:
   *  actual_input_eff (best available estimate — these rows didn't run
   *  pixelpipe or we can't measure what it would have cost, so the
   *  counterfactual ≈ actual).
   *
   *  This is the right denominator for "share of bill saved": dividing
   *  by what-you-would-have-paid is bounded at 100% (you can't save more
   *  than you would have spent). Dividing by what-you-DID-pay is not
   *  bounded — a single big cold-miss compressed request can make
   *  saved/actual exceed 100% because pixelpipe shrunk the actual to
   *  near zero. */
  allBaselineEquivalentWeighted: number;
  /** Sum of weighted ACTUAL input tokens across the same all-rows set.
   *  Kept for the diagnostic sub-line and the back-compat saved_usd math. */
  allActualInputWeighted: number;
  /** Sum of output_tokens × OUTPUT_TOKEN_RATE across the same all-rows set.
   *  Output is identical with/without compression, so it appears in both
   *  numerator and denominator at the same value and cancels in the savings
   *  numerator. Included in the denominator so the headline drops honestly
   *  toward zero on output-heavy workloads. */
  allOutputWeighted: number;
  /** Count of requests that contributed to allActualInputWeighted (had a
   *  usage block). Lets the UI annotate "N of M paid requests". */
  allUsageRequests: number;
  /** Direct compressed-vs-passthrough actual-cost split. No counterfactuals,
   *  no probe gating — just sum what each path actually billed.
   *
   *  These accumulate over `haveUsage` rows only (same gate as the all-rows
   *  counters above) and partition that set by `info.compressed`. The point
   *  is to answer "did the compressed path actually cost less per request
   *  than the passthrough path, on real traffic" without inventing a
   *  counterfactual. Selection bias is real (the gate decides which path
   *  each turn lands on), so the UI surfaces sample counts so the operator
   *  can judge sufficiency — the dashboard does not auto-claim significance. */
  compressedPaidRequests: number;
  compressedActualInputWeighted: number;
  compressedOutputWeighted: number;
  passthroughPaidRequests: number;
  passthroughActualInputWeighted: number;
  passthroughOutputWeighted: number;
  /** Sum of ground-truth output character counts from the SSE/JSON scanner
   *  (see `OutputMeasurement` in proxy.ts). These three accumulators are
   *  independent of Anthropic's `usage.output_tokens` — they let the operator
   *  compare what we measured vs what Anthropic billed and surface the gap
   *  the redacted_thinking opaque blocks create. Counted in Unicode code
   *  units (UTF-16 string .length). */
  textCharsMeasured: number;
  thinkingCharsMeasured: number;
  toolUseCharsMeasured: number;
  /** Number of `redacted_thinking` content blocks we saw. We can't read
   *  their length (server-encrypted bytes) so we count blocks instead. */
  redactedBlockCountMeasured: number;
  /** How many events contributed measurement counters. Lets the UI annotate
   *  the panel ("N of M events measured") when the scanner fell back. */
  eventsWithMeasurement: number;
  startedAt: number;
}

/*
 * ─────────────────────────────────────────────────────────────────────────
 *  PROVENANCE — every magic number below should trace to one of these:
 *
 *  [docs-pricing]   docs.anthropic.com/en/docs/about-claude/pricing
 *                   Verified 2026-05-19 via WebFetch. The page lists per-model
 *                   per-million-token rates and the cache-tier multipliers.
 *
 *  [count_tokens]   docs.anthropic.com/en/api/messages-count-tokens
 *                   The dashboard's baseline number comes from a free side
 *                   call to /v1/messages/count_tokens on the PRE-COMPRESSION
 *                   body. No estimation, no α, no regression.
 * ─────────────────────────────────────────────────────────────────────────
 */

/** Output-token rate multiplier (referenced to the input base rate).
 *  Source: [docs-pricing] — Opus 4.7 lists $5/Mtok input and $25/Mtok
 *  output (5×); Sonnet 4.7 lists $3/Mtok input and $15/Mtok output (5×).
 *  Same ratio holds on Haiku 4.5 ($1/$5). */
const OUTPUT_TOKEN_RATE = 5.0;

/** Per-million-token input rate ASSUMED for the headline dollar figure.
 *  Source: https://docs.claude.com/en/docs/about-claude/pricing — Opus 4.7
 *  input is $5/Mtok (same as Opus 4.5 / 4.6; the previous "$2.50" value
 *  here was a regression). Cache-write 5m = $6.25/Mtok (1.25×),
 *  cache-read = $0.50/Mtok (0.10×).
 *
 *  This is exposed on /proxy-stats as `pricing_assumptions.input_per_mtok`
 *  so the operator can see what we assumed and override if they're
 *  running against a non-default deployment (Bedrock/Vertex add a 10%
 *  premium; Sonnet would be $3/Mtok, etc.).
 *
 *  NOTE: Opus 4.7 uses a different tokenizer than 4.5/4.6 (per
 *  docs.claude.com/en/docs/about-claude/pricing), so even at the same
 *  $/Mtok rate, the same string maps to a different token count. The
 *  honest oracle for "tokens in this body" is `count_tokens` against the
 *  actual target model; do not trust hardcoded chars-per-token or
 *  tokens-per-image constants on 4.7 without verifying against the
 *  upstream probe. */
export const ASSUMED_INPUT_USD_PER_MTOK = 5.0;

export class DashboardState {
  private recent: RecentRow[] = [];
  /** Per-session dollar-weighted totals, keyed by `info.firstUserSha8`. The
   *  dashboard surfaces ONLY the most-recently-active session via the
   *  `serveCurrentSessionJson` endpoint — older sessions linger in the Map
   *  so a tab refresh during a brief lull still finds the previous session,
   *  but get evicted at `SESSION_CAP` to bound memory in long-running hosts. */
  private sessions: Map<string, SessionTotals> = new Map();
  /** sha8 of the most-recently-active session id. null when no events have
   *  ever carried a `firstUserSha8` (e.g. a cold start with only passthrough
   *  hits that the upstream probe never tagged). */
  private currentSessionId: string | null = null;
  /** Hard cap on `sessions` Map entries. Keeps memory bounded in
   *  long-running deployments. 50 sessions × ~13 numeric fields each is
   *  comfortably under a MB even with fat bucket/passthrough histograms. */
  private static readonly SESSION_CAP = 50;
  private totals: Totals = {
    requests: 0,
    compressedRequests: 0,
    actualInputWeighted: 0,
    baselineInputWeighted: 0,
    outputWeighted: 0,
    allBaselineEquivalentWeighted: 0,
    allActualInputWeighted: 0,
    allOutputWeighted: 0,
    allUsageRequests: 0,
    compressedPaidRequests: 0,
    compressedActualInputWeighted: 0,
    compressedOutputWeighted: 0,
    passthroughPaidRequests: 0,
    passthroughActualInputWeighted: 0,
    passthroughOutputWeighted: 0,
    textCharsMeasured: 0,
    thinkingCharsMeasured: 0,
    toolUseCharsMeasured: 0,
    redactedBlockCountMeasured: 0,
    eventsWithMeasurement: 0,
    startedAt: Date.now() / 1000,
  };
  /** Bounded ring of the most recently rendered images (last IMAGE_RING_CAP).
   *  Each request that rendered an image pushes one entry; the matching
   *  RecentRow carries `img_id` so the dashboard can pull any image still in
   *  the ring via /proxy-latest-png?id=N. In-memory only — images are never
   *  persisted, so a restart starts this empty. */
  private images: ImageEntry[] = [];
  /** Monotonic image id source. Never reset, never reused — an evicted id
   *  stays dangling on its RecentRow rather than pointing at a new image. */
  private nextImageId = 1;
  /** Runtime kill switch for compression. When false, the proxy forwards
   *  /v1/messages unchanged to upstream — pure passthrough, no images,
   *  no transforms. Controlled by the dashboard "passthrough" toggle so
   *  the operator can disable the proxy's transform instantly when
   *  upstream is unhealthy or when triaging a bad release. In-memory
   *  only — restart resets to true. */
  private compressionEnabled = true;
  setCompressionEnabled(on: boolean): void {
    this.compressionEnabled = on;
  }
  getCompressionEnabled(): boolean {
    return this.compressionEnabled;
  }
  /** Resolved disk paths for the events.jsonl + 4xx-bodies sidecar dir. The
   *  new sessions / cleanup endpoints need this; legacy callers that don't
   *  pass `paths` opt out of those endpoints by returning 503. */
  private readonly paths: SessionsPaths | undefined;

  /** Test hook: when set, /api/sessions.json and /api/sessions/${id}.json
   *  call this instead of `claudeCodeMap()` with the real `~/.claude/projects/`
   *  path. Lets unit tests run in tens of ms instead of scanning hundreds of
   *  the developer's actual Claude Code session files. */
  private readonly ccMapFn: () => Promise<Map<string, ClaudeCodeSessionRef>>;

  constructor(
    paths?: SessionsPaths,
    ccMapFn?: () => Promise<Map<string, ClaudeCodeSessionRef>>,
  ) {
    this.paths = paths;
    this.ccMapFn = ccMapFn ?? (() => claudeCodeMap());
  }

  /** Stash a rendered image into the ring (called from onRequest with the raw
   *  ProxyEvent before info.firstImagePng is dropped by toTrackEvent).
   *  Returns the assigned image id, or undefined when there's no image —
   *  the caller stamps it onto the RecentRow as `img_id`. */
  captureImage(info: NonNullable<ProxyEvent['info']>): number | undefined {
    if (!info.firstImagePng) return undefined;
    const id = this.nextImageId++;
    const width = info.firstImageWidth ?? 0;
    const height = info.firstImageHeight ?? 0;
    const kb = (info.firstImagePng.length / 1024).toFixed(1);
    const meta =
      `${width}×${height} · ${kb} KB · ` +
      `${info.imageCount ?? 0} image${info.imageCount === 1 ? '' : 's'} total`;
    this.images.push({
      id,
      png: info.firstImagePng,
      meta,
      width,
      height,
      ts: Date.now() / 1000,
    });
    // Evict the oldest entries past the cap. splice() keeps insertion order
    // so images[images.length - 1] is always the latest render.
    if (this.images.length > IMAGE_RING_CAP) {
      this.images.splice(0, this.images.length - IMAGE_RING_CAP);
    }
    return id;
  }

  /** Fold one event into the running totals + ring buffer.
   *
   *  Savings math is gated on a per-request `baseline_tokens` measurement
   *  from the parallel count_tokens probe AND an upstream usage block.
   *  When either is missing, we still count the request but skip its
   *  savings contribution — no estimation. */
  update(ev: ProxyEvent): void {
    // Stash the image bytes before they get GC'd by the request finishing.
    // The returned id (if any) is stamped onto this request's RecentRow so
    // the dashboard can pull the exact image that request rendered.
    const imgId = ev.info ? this.captureImage(ev.info) : undefined;

    const u = ev.usage;
    const info = ev.info;
    const compressed = info?.compressed === true;

    const inp = u?.input_tokens ?? 0;
    const out = u?.output_tokens ?? 0;
    const cc = u?.cache_creation_input_tokens ?? 0;
    const cr = u?.cache_read_input_tokens ?? 0;
    const haveUsage = u !== undefined && (inp > 0 || out > 0 || cc > 0 || cr > 0);
    const baseline = info?.baselineTokens;
    // Honest gating: only attribute savings when BOTH baseline probes
    // resolved (status === 'ok'). When the cacheable-prefix probe failed
    // (status === 'partial') we previously fell through to cacheable=0,
    // which silently charges the unproxied counterfactual the cold-input
    // rate on tokens that actually would have been cache-discounted —
    // fabricating "$ saved". Excluding the row is the only honest move
    // until the probe succeeds.
    const probeOk = info?.baselineProbeStatus === 'ok'
      // Back-compat: hosts that haven't adopted baselineProbeStatus yet
      // still see fields land; we accept legacy rows where the full-body
      // probe resolved AND (either no markers existed OR cacheable did too).
      || (info?.baselineProbeStatus === undefined && baseline !== undefined && baseline > 0);
    const haveBaseline = typeof baseline === 'number' && baseline > 0 && probeOk;

    // Weighted INPUT cost we actually paid this turn.
    const actualInputEff = haveUsage ? computeActualInputEff(inp, cc, cr) : 0;

    // Cache-aware baseline: decompose the unproxied counterfactual into
    // (cacheable_prefix, cold_tail) using the second count_tokens probe,
    // then split the prefix into (cc_u, cr_u) using the SAME absolute
    // cc bucket the proxied path paid this turn — because user-typed
    // content (the new tail that becomes cc) is NOT compressed, so its
    // absolute token count is approximately the same on both paths.
    // See src/core/baseline.ts for the full derivation and the May-2026
    // regression that motivated the rewrite.
    const baselineInputEff =
      haveBaseline && haveUsage
        ? computeBaselineInputEff(
            baseline,
            info?.baselineCacheableTokens ?? 0,
            cc,
            cr,
          )
        : 0;

    // Output tokens are identical with/without compression — the proxy never
    // touches the response body. They show up on BOTH sides of the savings
    // ratio at their actual rate (OUTPUT_TOKEN_RATE × input rate) so the
    // denominator reflects the full bill the user actually pays. Without
    // this, an output-heavy turn would silently inflate the "saved %"
    // headline relative to what Anthropic's weekly limit meters as token
    // consumption (input + output × 5).
    const outputEquiv = haveUsage ? out * OUTPUT_TOKEN_RATE : 0;

    this.totals.requests += 1;
    if (compressed) this.totals.compressedRequests += 1;

    if (haveBaseline && haveUsage) {
      this.totals.baselineInputWeighted += baselineInputEff;
      this.totals.actualInputWeighted += actualInputEff;
      this.totals.outputWeighted += outputEquiv;
    }
    // All-rows COUNTERFACTUAL spend, ungated on the probe — the honest
    // denominator for "did pixelpipe move my real bill". Measured rows
    // contribute their cache-aware baseline (what the unproxied path
    // would have billed); unmeasured/probe-failed/passthrough rows
    // contribute their actual input (pixelpipe either didn't run or we
    // can't measure the counterfactual, so actual ≈ baseline). This
    // keeps the ratio bounded at 100% — you can't save more than you
    // would have paid.
    if (haveUsage) {
      this.totals.allBaselineEquivalentWeighted +=
        haveBaseline ? baselineInputEff : actualInputEff;
      this.totals.allActualInputWeighted += actualInputEff;
      this.totals.allOutputWeighted += outputEquiv;
      this.totals.allUsageRequests += 1;
      // Direct observed compressed-vs-passthrough split. No counterfactual,
      // no probe gating — just partition the paid-rows set by which path
      // actually ran this turn. Headline answers "is the compressed path
      // cheaper per request on real traffic". Selection bias (the gate
      // routes each turn) is real; sample counts go to the UI so the
      // operator can judge sufficiency.
      if (compressed) {
        this.totals.compressedPaidRequests += 1;
        this.totals.compressedActualInputWeighted += actualInputEff;
        this.totals.compressedOutputWeighted += outputEquiv;
      } else {
        this.totals.passthroughPaidRequests += 1;
        this.totals.passthroughActualInputWeighted += actualInputEff;
        this.totals.passthroughOutputWeighted += outputEquiv;
      }
    }

    // Per-session aggregation. Uses the SAME baseline/actual/output math as
    // the global accumulators above, partitioned by `info.firstUserSha8`
    // so the dashboard's "current session" panel can show what's happening
    // RIGHT NOW instead of stale lifetime numbers. Untagged events (no
    // firstUserSha8 — cold start, passthrough probe failures) are skipped
    // rather than bucketed into a synthetic "unknown" session.
    const sid = info?.firstUserSha8;
    if (typeof sid === 'string' && sid.length > 0) {
      this.currentSessionId = sid;
      let s = this.sessions.get(sid);
      if (!s) {
        s = {
          sessionId: sid,
          firstSeen: Date.now() / 1000,
          lastSeen: Date.now() / 1000,
          requests: 0,
          baselineInputWeighted: 0,
          actualInputWeighted: 0,
          outputWeighted: 0,
          bucketChars: {},
          passthroughReasons: {},
          passthroughRequests: 0,
          compressedRequests: 0,
        };
        this.sessions.set(sid, s);
        // Cap memory — drop the oldest session by lastSeen when over budget.
        if (this.sessions.size > DashboardState.SESSION_CAP) {
          const oldest = [...this.sessions.values()].sort(
            (a, b) => a.lastSeen - b.lastSeen,
          )[0];
          if (oldest) this.sessions.delete(oldest.sessionId);
        }
      }
      s.lastSeen = Date.now() / 1000;
      s.requests += 1;
      // Reuse the same haveUsage / haveBaseline guards + the
      // baselineInputEff / actualInputEff / outputEquiv locals computed
      // earlier in update() so the lifetime totals block (above) and the
      // per-session block (here) read the same values. Re-deriving them
      // here would duplicate the cache-aware-baseline math and invite drift.
      if (haveBaseline && haveUsage) {
        s.baselineInputWeighted += baselineInputEff;
        s.actualInputWeighted += actualInputEff;
        s.outputWeighted += outputEquiv;
      }
      if (compressed) s.compressedRequests += 1;
      else s.passthroughRequests += 1;
      // Per-bucket char attribution from `info.bucketChars` (flat
      // `Partial<Record<BucketName, number>>` — see src/core/tracker.ts).
      // Matches the shape the Svelte panel iterates over.
      const bc = info?.bucketChars;
      if (bc && typeof bc === 'object') {
        for (const [key, val] of Object.entries(bc) as [string, unknown][]) {
          if (typeof val === 'number' && Number.isFinite(val)) {
            s.bucketChars[key] = (s.bucketChars[key] ?? 0) + val;
          }
        }
      }
      // Passthrough reason histogram from `info.passthroughReasons`.
      const pr = info?.passthroughReasons;
      if (pr && typeof pr === 'object') {
        for (const [reason, count] of Object.entries(pr as Record<string, unknown>)) {
          if (typeof count === 'number' && Number.isFinite(count) && count > 0) {
            s.passthroughReasons[reason] = (s.passthroughReasons[reason] ?? 0) + count;
          }
        }
      }
    }

    // Measurement totals are independent of usage/baseline gating — they
    // accumulate whenever the scanner produced numbers. The scanner sets
    // measurement to undefined on 5xx (no body to scan) and on unknown
    // content-types; we count an event as "measured" when it has any.
    const m = ev.measurement;
    if (m) {
      this.totals.textCharsMeasured += m.textChars;
      this.totals.thinkingCharsMeasured += m.thinkingChars;
      this.totals.toolUseCharsMeasured += m.toolUseChars;
      this.totals.redactedBlockCountMeasured += m.redactedBlockCount;
      this.totals.eventsWithMeasurement += 1;
    }

    const row: RecentRow = {
      ts: Date.now() / 1000,
      method: ev.method,
      path: ev.path,
      status: ev.status,
      compressed,
      cc_added: compressed ? 1 : undefined,
      input_tokens: haveUsage ? inp : undefined,
      output_tokens: haveUsage ? out : undefined,
      cache_create: haveUsage ? cc : undefined,
      cache_read: haveUsage ? cr : undefined,
      actual_input: haveUsage ? round1(actualInputEff) : undefined,
      baseline_input: haveBaseline && haveUsage ? round1(baselineInputEff) : undefined,
      session_saved_so_far_delta:
        haveBaseline && haveUsage ? round1(baselineInputEff - actualInputEff) : undefined,
      img_id: imgId,
    };
    this.recent.push(row);
    if (this.recent.length > RECENT_CAP) this.recent.splice(0, this.recent.length - RECENT_CAP);
  }


  /** On startup, fold the last N entries from the JSONL events file back
   *  into the ring buffer so a process restart doesn't show an empty table.
   *  Cumulative totals are *not* restored (the file may have rotated, and
   *  double-counting is worse than starting fresh). */
  async replay(filePath: string): Promise<void> {
    try {
      await fs.promises.access(filePath, fs.constants.R_OK);
    } catch {
      return; // no file yet, nothing to replay
    }
    const stream = fs.createReadStream(filePath, { encoding: 'utf8' });
    const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });
    const tail: TrackEvent[] = [];
    for await (const line of rl) {
      if (!line) continue;
      try {
        const ev = JSON.parse(line) as TrackEvent;
        tail.push(ev);
        if (tail.length > RECENT_CAP) tail.shift();
      } catch {
        /* skip malformed line */
      }
    }
    for (const t of tail) {
      const inp = t.input_tokens ?? 0;
      const out = t.output_tokens ?? 0;
      const cc = t.cache_create_tokens ?? 0;
      const cr = t.cache_read_tokens ?? 0;
      const haveUsage = inp > 0 || out > 0 || cc > 0 || cr > 0;
      const baseline = (t as { baseline_tokens?: number }).baseline_tokens;
      const cacheable = (t as { baseline_cacheable_tokens?: number })
        .baseline_cacheable_tokens ?? 0;
      const probeStatus = (t as { baseline_probe_status?: string }).baseline_probe_status;
      // Same gating rule as update(): require an explicit 'ok' status when
      // present; fall back to "have a baseline number" for legacy JSONL.
      const probeOk = probeStatus === 'ok'
        || (probeStatus === undefined && typeof baseline === 'number' && baseline > 0);
      const haveBaseline = typeof baseline === 'number' && baseline > 0 && probeOk;
      const actualInputEff = haveUsage ? computeActualInputEff(inp, cc, cr) : 0;
      const baselineInputEff =
        haveBaseline && haveUsage
          ? computeBaselineInputEff(baseline as number, cacheable, cc, cr)
          : 0;
      // Output tokens land in the row for the table; totals are not
      // restored on replay (see header comment on cumulative totals).
      const row: RecentRow = {
        ts: Date.parse(t.ts) / 1000,
        method: t.method,
        path: t.path,
        status: t.status,
        compressed: t.compressed === true,
        cc_added: t.compressed === true ? 1 : undefined,
        input_tokens: t.input_tokens,
        output_tokens: t.output_tokens,
        cache_create: t.cache_create_tokens,
        cache_read: t.cache_read_tokens,
        actual_input: haveUsage ? round1(actualInputEff) : undefined,
        baseline_input:
          haveBaseline && haveUsage ? round1(baselineInputEff) : undefined,
      };
      this.recent.push(row);
    }
  }

  // ---- HTTP handlers ------------------------------------------------------

  /**
   * Per-session "what's happening right now" payload backing the
   * `SessionSummary` panel. Scopes the dollar-weighted savings ratio + the
   * per-bucket char attribution + the passthrough-reason histogram to the
   * most-recently-active session (tracked via `info.firstUserSha8`) so the
   * top-of-dashboard headline reflects the live session rather than stale
   * lifetime aggregates from a previous run.
   *
   * Returns `{ sessionId: null, message: 'no active session yet' }` when no
   * events have been received yet (or the first events were all untagged —
   * cold start, probe failures) — `update()` only sets `currentSessionId`
   * when a `firstUserSha8`-tagged event lands. The client renders a stale
   * panel rather than zeroes when a session goes idle (NO `lastSeen >
   * threshold` check here; see comment in `update()` for the rationale).
   */
  serveCurrentSessionJson(): Response {
    if (!this.currentSessionId) {
      return jsonResponse({
        sessionId: null,
        message: 'no active session yet',
      });
    }
    const s = this.sessions.get(this.currentSessionId);
    if (!s) {
      return jsonResponse({ sessionId: null, message: 'no active session yet' });
    }
    // Dollar-weighted savings ratio. Same math as the global `saved_pct`
    // (compressed AND passthrough requests — passthrough has baseline=actual,
    // so it correctly drags the ratio down when we leak). Honest denominator:
    // includes both compressed and uncompressed flows that the proxy saw.
    const baselineUsd = (s.baselineInputWeighted * ASSUMED_INPUT_USD_PER_MTOK) / 1e6;
    const actualUsd = (s.actualInputWeighted * ASSUMED_INPUT_USD_PER_MTOK) / 1e6;
    const savedUsd = baselineUsd - actualUsd;
    const savedPct = baselineUsd > 0 ? (savedUsd / baselineUsd) * 100 : 0;
    return jsonResponse({
      sessionId: s.sessionId,
      firstSeen: s.firstSeen,
      lastSeen: s.lastSeen,
      uptimeSec: Math.max(0, s.lastSeen - s.firstSeen),
      requests: s.requests,
      compressedRequests: s.compressedRequests,
      passthroughRequests: s.passthroughRequests,
      baselineUsd: round4(baselineUsd),
      actualUsd: round4(actualUsd),
      savedUsd: round4(savedUsd),
      savedPct: round1(savedPct),
      bucketChars: s.bucketChars,
      passthroughReasons: s.passthroughReasons,
    });
  }

  serveStats(): Response {
    // Two headline numbers, derived from the same per-event accumulators:
    //
    //   saved_pct_input_only = Σ saved / Σ baseline_input_eff × 100
    //     What the proxy actually saved on the slice it can move (input).
    //     Numerator = input tokens we didn't pay for (cache-aware).
    //     Denominator = input tokens we WOULD have paid (cache-aware).
    //     Output is excluded because the proxy doesn't touch it.
    //
    //   saved_pct_of_total_bill = Σ saved / Σ (baseline_input + output × 5) × 100
    //     What share of the TOTAL bill the proxy saved. Honest counter to the
    //     input-only number: on output-heavy sessions (long thinking blocks,
    //     big edits) the percentage shrinks because output dominates.
    //
    //   token_equivalent_total = Σ (actual_input + output × 5)
    //     What Anthropic's weekly limit actually meters — input × 1.0 +
    //     output × 5.0 (the same ratio as the per-MTok price card). This is
    //     the number that moves your "%% used this week" indicator.
    const baseline = this.totals.baselineInputWeighted;
    const actual = this.totals.actualInputWeighted;
    const output = this.totals.outputWeighted; // already × OUTPUT_TOKEN_RATE
    const saved = baseline - actual;
    const pctInput = baseline > 0 ? (saved / baseline) * 100 : 0;
    const baselineTotal = baseline + output;
    const actualTotal = actual + output;
    const pctTotal = baselineTotal > 0 ? (saved / baselineTotal) * 100 : 0;

    // Share-of-all-spend: honest denominator. The numerator can only credit
    // savings against rows where we have a probe baseline (otherwise it's
    // estimation), but the denominator MUST include every request the user
    // actually paid for — including passthrough rows, probe-failed rows,
    // and untransformed turns the gate said no to. Otherwise the headline
    // answers "did pixelpipe help on the rows where it ran" instead of
    // "did pixelpipe move my real bill". The first is a cherry-pick.
    const allBaselineEquiv = this.totals.allBaselineEquivalentWeighted;
    const allActual = this.totals.allActualInputWeighted;
    const allOutput = this.totals.allOutputWeighted;
    // Denominator = counterfactual all-rows bill: what the user would have
    // paid with no pixelpipe. Bounded ratio at 100%; a single cold-miss
    // compressed request on an otherwise empty session shows ~99% saved,
    // not 280%.
    const allCounterfactualBill = allBaselineEquiv + allOutput;
    const pctAllSpend =
      allCounterfactualBill > 0 ? (saved / allCounterfactualBill) * 100 : 0;

    // Direct observed split — actual $ per request, partitioned by which
    // path ran. Token-equivalent (input × 1.0 + cache_create × 1.25 +
    // cache_read × 0.10 + output × 5) → $ at the assumed Opus 4.7 input
    // rate. Same $/Mtok rate is applied to both buckets, so the bias from
    // the rate assumption cancels in the delta. Selection bias from the
    // gate is NOT cancelled — the operator interprets that via the
    // sample-count caveat below.
    const compressedTokenEquiv =
      this.totals.compressedActualInputWeighted +
      this.totals.compressedOutputWeighted;
    const passthroughTokenEquiv =
      this.totals.passthroughActualInputWeighted +
      this.totals.passthroughOutputWeighted;
    const compressedActualUsd =
      (compressedTokenEquiv * ASSUMED_INPUT_USD_PER_MTOK) / 1e6;
    const passthroughActualUsd =
      (passthroughTokenEquiv * ASSUMED_INPUT_USD_PER_MTOK) / 1e6;
    const compressedAvgUsd =
      this.totals.compressedPaidRequests > 0
        ? compressedActualUsd / this.totals.compressedPaidRequests
        : 0;
    const passthroughAvgUsd =
      this.totals.passthroughPaidRequests > 0
        ? passthroughActualUsd / this.totals.passthroughPaidRequests
        : 0;
    // Sufficient-sample threshold is a soft heuristic. 20 paid requests per
    // bucket is enough to see a real effect on Opus 4.7 traffic (a single
    // big cold-miss can dominate at lower n). Below this, the UI shows the
    // bucket numbers but hides the delta and surfaces "small sample".
    const SUFFICIENT = 20;
    const splitSufficient =
      this.totals.compressedPaidRequests >= SUFFICIENT &&
      this.totals.passthroughPaidRequests >= SUFFICIENT;
    const splitDeltaUsd = compressedAvgUsd - passthroughAvgUsd;

    const uptimeSec = Date.now() / 1000 - this.totals.startedAt;
    const payload = {
      requests: this.totals.requests,
      compressed_requests: this.totals.compressedRequests,
      baseline_input_weighted: Math.round(baseline),
      actual_input_weighted: Math.round(actual),
      saved_input_tokens: Math.round(saved),
      // saved_pct kept for back-compat with existing dashboard HTML; it is
      // the input-only number. New code should read saved_pct_input_only.
      saved_pct: round1(pctInput),
      saved_pct_input_only: round1(pctInput),
      saved_pct_of_total_bill: round1(pctTotal),
      // Honest "share of total bill saved" — measured-rows numerator over
      // ALL paid requests in the denominator (compressed + passthrough +
      // probe-failed). This is the number users actually want when they
      // ask "is pixelpipe helping". Negative when flap-pollution from
      // passthrough turns exceeds the collapse win on measured turns.
      saved_pct_of_all_spend: round1(pctAllSpend),
      all_baseline_equivalent_weighted: Math.round(allBaselineEquiv),
      all_actual_input_weighted: Math.round(allActual),
      all_output_weighted: Math.round(allOutput),
      all_usage_requests: this.totals.allUsageRequests,
      // Direct observed split — replaces "share of spend saved" as the
      // headline. Total actual $ and average $/req per path, plus a delta
      // gated on `split_sufficient_sample`. No counterfactual: each
      // bucket is what each path actually billed.
      compressed_paid_requests: this.totals.compressedPaidRequests,
      passthrough_paid_requests: this.totals.passthroughPaidRequests,
      compressed_actual_usd: round4(compressedActualUsd),
      passthrough_actual_usd: round4(passthroughActualUsd),
      compressed_avg_usd_per_request: round4(compressedAvgUsd),
      passthrough_avg_usd_per_request: round4(passthroughAvgUsd),
      compressed_minus_passthrough_avg_usd: round4(splitDeltaUsd),
      split_sufficient_sample: splitSufficient,
      split_min_sample_per_bucket: SUFFICIENT,
      saved_usd: round4((saved * ASSUMED_INPUT_USD_PER_MTOK) / 1e6),
      output_weighted: Math.round(output),
      baseline_token_equivalent: Math.round(baselineTotal),
      actual_token_equivalent: Math.round(actualTotal),
      pricing_assumptions: {
        input_per_mtok: ASSUMED_INPUT_USD_PER_MTOK,
        output_multiplier: OUTPUT_TOKEN_RATE,
        cache_write_5m_multiplier: 1.25,
        cache_write_1h_multiplier: 2.0,
        cache_read_multiplier: 0.1,
        source: 'docs.anthropic.com/en/docs/about-claude/pricing (verified 2026-05-19)',
      },
      // Honest output measurement — char counts from the SSE/JSON scanner,
      // independent of Anthropic's `usage.output_tokens`. Surfaces the gap
      // the May-2026 weekly-meter audit hypothesized (redacted_thinking adds
      // billed tokens that we can't see). `events_with_measurement` lets the
      // operator weigh how representative the numbers are; when it's near
      // `requests`, the gap is real. When it's 0, the scanner never landed
      // (5xx-heavy session, no /v1/messages traffic).
      measured_text_chars: this.totals.textCharsMeasured,
      measured_thinking_chars: this.totals.thinkingCharsMeasured,
      measured_tool_use_chars: this.totals.toolUseCharsMeasured,
      measured_redacted_block_count: this.totals.redactedBlockCountMeasured,
      events_with_measurement: this.totals.eventsWithMeasurement,
      uptime_sec: uptimeSec,
      compression_enabled: this.compressionEnabled,
    };
    return new Response(JSON.stringify(payload, null, 2), {
      headers: { 'content-type': 'application/json', 'access-control-allow-origin': '*' },
    });
  }

  serveRecent(): Response {
    const latest = this.images[this.images.length - 1];
    const payload = {
      recent: this.recent,
      has_preview: latest !== undefined,
      preview_meta: latest?.meta ?? '',
      // Image ids currently resident in the ring. The dashboard uses this to
      // tell which RecentRow.img_id values still resolve — older ones have
      // been evicted and their "view" button should be disabled.
      image_ids: this.images.map((im) => im.id),
    };
    return new Response(JSON.stringify(payload), {
      headers: { 'content-type': 'application/json', 'access-control-allow-origin': '*' },
    });
  }

  /** GET /proxy-latest-png[?id=N] — raw PNG from the image ring. With no id
   *  (or an unknown id) the latest render is returned; ?id=N pulls that
   *  specific image while it's still in the ring. 404 once evicted. */
  servePng(id?: number): Response {
    // Cropping is done client-side via CSS (object-position + overflow:hidden).
    // Python decoded the PNG to crop server-side; we skip that to avoid
    // pulling a PNG decoder back in — the CSS approach renders identically.
    const entry =
      id !== undefined
        ? this.images.find((im) => im.id === id)
        : this.images[this.images.length - 1];
    if (!entry) {
      return new Response('no image yet', { status: 404 });
    }
    return new Response(entry.png as unknown as BodyInit, {
      headers: { 'content-type': 'image/png', 'cache-control': 'no-cache' },
    });
  }

  serveHtml(port: number): Response {
    return new Response(DASHBOARD_HTML.replace(/__PORT__/g, String(port)), {
      headers: { 'content-type': 'text/html; charset=utf-8' },
    });
  }

  // ---- session / cleanup endpoints --------------------------------------
  //
  // Every endpoint below recomputes from disk on demand. The dashboard polls
  // these on a 5s cadence, which is fine for a single-user dev tool — even at
  // ~3k events / 1.5 MB the round-trip is <100ms on a warm SSD.

  /** GET /api/sessions.json — grouped sessions enriched with the Claude Code
   *  cross-reference. The body is the top-level `sessions` array; the client
   *  renders a bar chart of the top savers. */
  async serveSessionsJson(opts: ListOptions = {}): Promise<Response> {
    if (!this.paths) return notConfigured('sessions');
    const [{ sessions }, ccMap] = await Promise.all([
      aggregateSessions(this.paths),
      this.ccMapFn(),
    ]);
    const rows = filterSessions(sessions, opts);
    const enriched = rows.map((s) => ({
      ...s,
      claudeCode: ccMap.get(s.id) ?? null,
    }));
    return jsonResponse({ sessions: enriched, count: enriched.length });
  }

  /** GET /api/stats.json — full-history aggregate. Migrated from the
   *  former `pixelpipe stats` CLI. */
  async serveApiStats(): Promise<Response> {
    if (!this.paths) return notConfigured('stats');
    const result = await aggregateEventsFile(this.paths.eventsFile);
    if (!result) {
      return jsonResponse({
        error: 'no events file yet',
        path: this.paths.eventsFile,
      }, 404);
    }
    return jsonResponse({
      parsed: result.parsed,
      dropped: result.dropped,
      summary: summaryToJson(result.summary),
    });
  }

  /** POST /api/compression — flip the runtime kill switch.
   *  Body: { enabled: boolean }. Returns the new state. In-memory only;
   *  restart resets to true. */
  handleCompressionToggle(body: { enabled?: unknown }): Response {
    const on = body.enabled === true;
    this.compressionEnabled = on;
    return jsonResponse({ compression_enabled: on });
  }
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'content-type': 'application/json',
      'access-control-allow-origin': '*',
    },
  });
}

function notConfigured(what: string): Response {
  // The dashboard was constructed without SessionsPaths (e.g. a legacy host
  // that doesn't track to disk). Return 503 so the client can surface a
  // helpful error rather than failing silently.
  return jsonResponse(
    { error: `${what} unavailable: dashboard not configured with event paths` },
    503,
  );
}

function round1(n: number): number {
  return Math.round(n * 10) / 10;
}
function round4(n: number): number {
  return Math.round(n * 10000) / 10000;
}

/** Result of route-matching a dashboard URL. The legacy `kind` values
 *  (html/stats/recent/png) stay alongside the `/api/*` JSON endpoints. */
export type DashboardRoute =
  | { kind: 'html' }
  | { kind: 'stats' } // /proxy-stats — legacy live counter
  | { kind: 'recent' } // /proxy-recent — legacy ring buffer
  | { kind: 'png' } // /proxy-latest-png
  | { kind: 'api-sessions' } // /api/sessions.json
  | { kind: 'api-stats' } // /api/stats.json
  | { kind: 'current-session' } // /api/current-session.json
  | { kind: 'api-compression' }; // /api/compression (POST {enabled}) — runtime kill switch

/** Match dashboard paths (handle query strings on /proxy-latest-png). */
export function dashboardPath(pathname: string): DashboardRoute | null {
  if (pathname === '/' || pathname === '/dashboard') return { kind: 'html' };
  if (pathname === '/proxy-stats') return { kind: 'stats' };
  if (pathname === '/proxy-recent') return { kind: 'recent' };
  if (pathname === '/proxy-latest-png') return { kind: 'png' };
  if (pathname === '/api/sessions.json') return { kind: 'api-sessions' };
  if (pathname === '/api/stats.json') return { kind: 'api-stats' };
  if (pathname === '/api/current-session.json') return { kind: 'current-session' };
  if (pathname === '/api/compression') return { kind: 'api-compression' };
  return null;
}

// ---- inline HTML template -------------------------------------------------

const DASHBOARD_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>pixelpipe – Live dashboard</title>
<style>
  /* Pre-mount body styling so the loading flash matches the Svelte UI. The
     real stylesheet is injected by Svelte components on mount. */
  * { box-sizing: border-box; }
  body { margin: 0; padding: 0; background: #0d1117; color: #c9d1d9;
         font: 14px/1.45 -apple-system,BlinkMacSystemFont,"SF Mono",Menlo,monospace; }
  #app:empty::before { content: 'pixelpipe dashboard loading…';
                       display: block; padding: 24px; color: #6e7681; }
</style>
</head>
<body>
<div id="app"></div>
<script>${DASHBOARD_JS}</script>
</body></html>
`;
